// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repositories/product_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repositories/product_repository.go -destination=internal/mocks/product_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
